steps:
- id: 'Clone repo'
  # This step fetches the policies from the repository
  name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/pyljain/sdc-kcc-toolchain.git']
- id: 'Set namespace in manifests'
  # This step fetches the policies from the repository
  name: 'gcr.io/kpt-dev/kpt:latest'
  entrypoint: '/bin/sh'
  args: ['-c', 'kpt cfg set manifests/ namespace ${_NAMESPACE_NAME} -R']
- id: 'Set projectId in manifests'
  # This step fetches the policies from the repository
  name: 'gcr.io/kpt-dev/kpt:latest'
  entrypoint: '/bin/sh'
  args: ['-c', 'kpt cfg set manifests/ projectid sandbox-jainpayal -R']
- id: 'Apply the package'
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'manifests/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=activeassist-kcc'
# - id: 'Validate against policies'
  # This step validates resources against recommendations - do the docker way
  # name: 'gcr.io/kpt-dev/kpt'
  # args: ['-c', 'kpt fn run ../manifests/ --enable-exec --exec-path ./activeassist_run-macos']
# - id: "Run functions"
#   name: 'gcr.io/kpt-dev/kpt:latest'
#   args:
#     - fn
#     - run
    # - exmaple-package